# ESPHome HID Mouse - AI-Thinker ESP32-S3
# This config makes the mouse cursor move automatically for testing

esphome:
  name: ai-s3-mouse
  friendly_name: "AI-S3 HID Mouse"

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf
    version: recommended
    sdkconfig_options:
      # Disable USB-Serial/JTAG to free USB port for HID (REQUIRED)
      CONFIG_USJ_ENABLE_USB_SERIAL_JTAG: "n"
      # Enable TinyUSB HID (REQUIRED)
      CONFIG_TINYUSB_HID_COUNT: "1"
      # Console on UART0 for debugging (optional but recommended)
      CONFIG_ESP_CONSOLE_UART_DEFAULT: "y"
    components:
      - espressif/esp_tinyusb~2.0.0

# Load HID Mouse component
external_components:
  - source:
      type: local
      path: ../components
    components: [hid_mouse]

# HID Mouse
hid_mouse:
  id: my_mouse

# Logger (USB CDC disabled to avoid conflict with HID)
logger:
  level: DEBUG
  hardware_uart: UART0

# Automatic mouse movement every 2 seconds for testing
interval:
  - interval: 2s
    then:
      - lambda: |-
          // Random movement between -20 and +20 pixels
          int8_t x = (rand() % 41) - 20;
          int8_t y = (rand() % 41) - 20;
          ESP_LOGI("mouse", "Moving: x=%d, y=%d", x, y);
          id(my_mouse).move(x, y);
