# ESPHome configuration example for HID Mouse
# Compatible with ESP32-S3 native USB OTG

esphome:
  name: esp32-hid-mouse
  friendly_name: "ESP32 HID Mouse"
  platformio_options:
    board_build.flash_mode: dio

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf
    version: recommended

# Load external component
external_components:
  - source:
      type: git
      url: https://github.com/AntorFR/esphome-hid
      ref: main
    components: [hid_mouse]

# TinyUSB configuration (required for HID)
tinyusb:
  usb_product_str: "ESPHome HID Mouse"

# HID Mouse configuration
hid_mouse:
  id: my_mouse

# Optional: WiFi for debugging
# wifi:
#   ssid: "your-ssid"
#   password: "your-password"

# Optional: Logs
logger:
  level: DEBUG

# Example with physical buttons
binary_sensor:
  # Button for left click
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: true
    name: "Left Click"
    on_press:
      - hid_mouse.click:
          id: my_mouse
          button: LEFT

  # Button for right click
  - platform: gpio
    pin:
      number: GPIO1
      mode: INPUT_PULLUP
      inverted: true
    name: "Right Click"
    on_press:
      - hid_mouse.click:
          id: my_mouse
          button: RIGHT

# Example with an analog joystick
# sensor:
#   - platform: adc
#     pin: GPIO4
#     name: "Joystick X"
#     update_interval: 50ms
#     filters:
#       - calibrate_linear:
#           - 0.0 -> -127
#           - 1.65 -> 0
#           - 3.3 -> 127
#     on_value:
#       then:
#         - lambda: |-
#             int8_t x = (int8_t) x;
#             if (abs(x) > 5) {  // Dead zone
#               id(my_mouse).move(x / 10, 0);
#             }

# Interval for continuous movements
interval:
  - interval: 100ms
    then:
      - lambda: |-
          // Example: automatic circular movement
          // static float angle = 0;
          // angle += 0.1;
          // int8_t x = (int8_t)(cos(angle) * 5);
          // int8_t y = (int8_t)(sin(angle) * 5);
          // id(my_mouse).move(x, y);
