esphome:
  name: test-composite-telephony
  friendly_name: Test Composite Telephony
  platformio_options:
    board_build.flash_mode: dio

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  framework:
    type: esp-idf
    version: recommended
    sdkconfig_options:
      CONFIG_USJ_ENABLE_USB_SERIAL_JTAG: "n"
      CONFIG_TINYUSB_HID_COUNT: "1"
      CONFIG_ESP_CONSOLE_UART_DEFAULT: "y"
    components:
      - espressif/esp_tinyusb~2.0.0

logger:
  hardware_uart: UART0

external_components:
  - source:
      type: local
      path: ../components

hid_composite:
  id: my_hid

binary_sensor:
  - platform: hid_composite
    type: connected
    name: "PC Connected"
    id: pc_connected
  
  - platform: hid_composite
    type: muted
    name: "Muted"
    id: is_muted
  
  - platform: hid_composite
    type: in_call
    name: "In Call"
    id: is_in_call
  
  - platform: hid_composite
    type: ringing
    name: "Ringing"
    id: is_ringing

button:
  # Mouse actions
  - platform: template
    name: "Move Mouse"
    on_press:
      - hid_composite.move:
          x: 10
          y: 10
  
  # Keyboard actions
  - platform: template
    name: "Type Hello"
    on_press:
      - hid_composite.type:
          text: "Hello World!"
          speed: 100
          jitter: 30
  
  # Telephony actions
  - platform: template
    name: "Toggle Mute"
    on_press:
      - hid_composite.toggle_mute:
  
  - platform: template
    name: "Mute"
    on_press:
      - hid_composite.mute:
  
  - platform: template
    name: "Unmute"
    on_press:
      - hid_composite.unmute:
  
  - platform: template
    name: "Answer Call"
    on_press:
      - hid_composite.answer_call:
  
  - platform: template
    name: "Hang Up"
    on_press:
      - hid_composite.hang_up:
