esphome:
  name: test-keyboard-switch

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf
    version: recommended
    sdkconfig_options:
      CONFIG_USJ_ENABLE_USB_SERIAL_JTAG: "n"
      CONFIG_TINYUSB_HID_COUNT: "1"
      CONFIG_ESP_CONSOLE_UART_DEFAULT: "y"
    components:
      - espressif/esp_tinyusb^2.0.1

logger:
  hardware_uart: UART0

external_components:
  - source:
      type: local
      path: ../components
    components: [hid_keyboard]

hid_keyboard:
  id: my_keyboard

# Test binary sensor for connection status
binary_sensor:
  - platform: hid_keyboard
    name: "PC Connected"

# Test switch
switch:
  - platform: hid_keyboard
    name: "Keep Awake"
    key: "SCROLL_LOCK"
    interval: 30s
    jitter: 5s

# Test actions
button:
  - platform: template
    name: "Type Hello"
    on_press:
      - hid_keyboard.type:
          text: "Hello World!"
          speed: 80
          jitter: 20
  
  - platform: template
    name: "Start Keep Awake"
    on_press:
      - hid_keyboard.start_keep_awake:
          key: "F15"
          interval: 60s
          jitter: 10s
  
  - platform: template
    name: "Stop Keep Awake"
    on_press:
      - hid_keyboard.stop_keep_awake:
