# Minimal test configuration - Random mouse movements
# Flash via USB, then plug into a computer to see the mouse move
# The mouse will start moving automatically every 2 seconds!

esphome:
  name: esp32-hid-test
esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf
    sdkconfig_options:
      # Disable USB-Serial/JTAG to free USB port for HID (REQUIRED)
      CONFIG_USJ_ENABLE_USB_SERIAL_JTAG: "n"
      # Enable TinyUSB HID (REQUIRED)
      CONFIG_TINYUSB_HID_COUNT: "1"
      # Console on UART0 for debugging (recommended)
      CONFIG_ESP_CONSOLE_UART_DEFAULT: "y"
    components:
      - espressif/esp_tinyusb~2.0.0

# Load external component from local path for testing
external_components:
  - source:
      type: local
      path: ../components
    components: [hid_mouse]

# HID Mouse
hid_mouse:
  id: mouse

# Logs on UART0 (USB is used for HID)
logger:
  level: DEBUG
  hardware_uart: UART0

# Random mouse movement every 2 seconds - starts automatically!
interval:
  - interval: 2s
    then:
      - lambda: |-
          // Generate random movement between -20 and 20
          int8_t x = (rand() % 41) - 20;
          int8_t y = (rand() % 41) - 20;
          ESP_LOGI("test", "Moving mouse: x=%d, y=%d", x, y);
          id(mouse).move(x, y);
