esphome:
  name: test-keyboard-simple

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf
    version: recommended
    sdkconfig_options:
      CONFIG_USJ_ENABLE_USB_SERIAL_JTAG: "n"
      CONFIG_TINYUSB_HID_COUNT: "1"
      CONFIG_ESP_CONSOLE_UART_DEFAULT: "y"
    components:
      - espressif/esp_tinyusb^2.0.1

logger:
  hardware_uart: UART0

external_components:
  - source:
      type: local
      path: ../components
    components: [hid_keyboard]

hid_keyboard:
  id: my_keyboard

# Test actions
button:
  - platform: template
    name: "Type Hello"
    on_press:
      - hid_keyboard.type:
          text: "Hello World!"
          speed: 50
          jitter: 20
  
  - platform: template
    name: "Press Enter"
    on_press:
      - hid_keyboard.tap:
          key: "ENTER"
