esphome:
  name: test-composite-switch

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf
    version: recommended
    sdkconfig_options:
      CONFIG_USJ_ENABLE_USB_SERIAL_JTAG: "n"
      CONFIG_TINYUSB_HID_COUNT: "1"
      CONFIG_ESP_CONSOLE_UART_DEFAULT: "y"
    components:
      - espressif/esp_tinyusb^2.0.1

logger:
  hardware_uart: UART0

external_components:
  - source:
      type: local
      path: ../components
    components: [hid_composite]

hid_composite:
  id: my_hid

# Test switches
switch:
  - platform: hid_composite
    type: mouse
    name: "Mouse Keep Awake"
    interval: 30s
    jitter: 5s
  
  - platform: hid_composite
    type: keyboard
    name: "Keyboard Keep Awake"
    key: "F15"
    interval: 45s
    jitter: 10s

# Test actions
button:
  - platform: template
    name: "Move Mouse"
    on_press:
      - hid_composite.move:
          x: 10
          y: 10

  - platform: template
    name: "Type Hello"
    on_press:
      - hid_composite.type:
          text: "Hello World!"
          speed: 80
          jitter: 20

  - platform: template
    name: "Start Mouse Keep Awake"
    on_press:
      - hid_composite.start_mouse_keep_awake:
          interval: 60s
          jitter: 10s

  - platform: template
    name: "Stop Mouse Keep Awake"  
    on_press:
      - hid_composite.stop_mouse_keep_awake:

  - platform: template
    name: "Start Keyboard Keep Awake"
    on_press:
      - hid_composite.start_keyboard_keep_awake:
          key: "SCROLL_LOCK"
          interval: 60s
          jitter: 10s

  - platform: template
    name: "Stop Keyboard Keep Awake"
    on_press:
      - hid_composite.stop_keyboard_keep_awake:
